/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uasd;

import java.sql.SQLException;

/**
 *
 * @author jomil
 */
public class frameCatalogoUASD extends javax.swing.JFrame {
    
    //private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frameCatalogoUASD.class.getName());

    /**
     * Creates new form frameCatalogoUASD
     */
    Controlador c = new Controlador();
    public frameCatalogoUASD() {
        initComponents();
        System.out.println("Hola desde frameCatalogoUASD");
        try {
            c.mostrarFacultades(this);
        } catch (SQLException ex) {
            System.getLogger(frameCatalogoUASD.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (ClassNotFoundException ex) {
            System.getLogger(frameCatalogoUASD.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnMostrarFacultades = new javax.swing.JButton();
        btnMostrarEscuelas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.setName(""); // NOI18N
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        tabla.getAccessibleContext().setAccessibleName("");

        btnMostrarFacultades.setText("Mostrar Facultades");
        btnMostrarFacultades.setName(""); // NOI18N
        btnMostrarFacultades.addActionListener(this::btnMostrarFacultadesActionPerformed);

        btnMostrarEscuelas.setText("Mostrar Escuelas");
        btnMostrarEscuelas.addActionListener(this::btnMostrarEscuelasActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMostrarFacultades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrarEscuelas))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarFacultades)
                    .addComponent(btnMostrarEscuelas))
                .addGap(30, 30, 30))
        );

        btnMostrarFacultades.getAccessibleContext().setAccessibleName("btnMostrarFacultades");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarFacultadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarFacultadesActionPerformed
        try {
            // TODO add your handling code here:
            c.mostrarFacultades(this);
        } catch (SQLException ex) {
            System.getLogger(frameCatalogoUASD.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (ClassNotFoundException ex) {
            System.getLogger(frameCatalogoUASD.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnMostrarFacultadesActionPerformed

    private void btnMostrarEscuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarEscuelasActionPerformed
        try {
            // TODO add your handling code here:
            c.mostrarEscuelas(this);
        } catch (SQLException ex) {
            System.getLogger(frameCatalogoUASD.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (ClassNotFoundException ex) {
            System.getLogger(frameCatalogoUASD.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnMostrarEscuelasActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        if(this.tabla.getColumnName(0).equals("Nombre de Escuelas")){
            try {
                c.mostrarCarreras(this);
            } catch (SQLException ex) {
                System.getLogger(frameCatalogoUASD.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            } catch (ClassNotFoundException ex) {
                System.getLogger(frameCatalogoUASD.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }else if(this.tabla.getColumnName(0).equals("Nombre de Facultades")){
            try {
                c.mostrarEscuelas(this);
            } catch (SQLException ex) {
                System.getLogger(frameCatalogoUASD.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            } catch (ClassNotFoundException ex) {
                System.getLogger(frameCatalogoUASD.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnMostrarEscuelas;
    public javax.swing.JButton btnMostrarFacultades;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
